apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aspnet-todo-ui-mvc
  labels:
    name: aspnet-todo-ui-mvc
spec:
  selector:
    matchLabels:
      app: ui-mvc
  namespaceSelector:
    matchNames:
    - aspnet-todo
  endpoints:
  - port: "http"