apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-worker1-local-storage
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/k8s-worker1-local-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          # I've bound this PV to a specific node. This way we can keep the data retained on a single node, as it's set to a local path on the node.
          # Kubernetes will make sure to schedule pods into this node only to consume the storage.
          - k8s-worker1 