apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: aspnet-todo
  name: ui-mvc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-mvc
  template:
    metadata:
      labels:
        app: ui-mvc
    spec:
      containers:
      - name: aspnet-todo-ui-mvc
        image: ghcr.io/tiagogauziski/todolist-ui-mvc:main
        imagePullPolicy: Always
        env:
        - name: TodoApi__BaseAddress
          value: "http://api-service.aspnet-todo.svc.cluster.local:80/"
        - name: TodoApplication__BasePath
          value: "/aspnet-todo"
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 2
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: ui-mvc-service
  namespace: aspnet-todo
spec:
  selector:
    app: ui-mvc
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: https
      protocol: TCP
      port: 443
      targetPort: https
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui-mvc-ingress
  namespace: aspnet-todo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /aspnet-todo(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: ui-mvc-service
            port:
              number: 80